import { Box, Container, Flex, Link, Section, Text } from "@radix-ui/themes";
import { SectionTitle } from "../../components/ui";
import { GitHubLogoIcon, OpenInNewWindowIcon } from "@radix-ui/react-icons";
import tgImg from "../../assets/ticketguru_screenshot_small.png";

export default function TicketguruPage() {
  return (
    <Section py="4">
      <Container size="1">
        <Flex justify="center">
          <img
            src={tgImg}
            alt="Ticketguru login screen"
            style={{
              height: "auto",
            }}
          />
        </Flex>
      </Container>

      <SectionTitle>Ticketguru</SectionTitle>
      <Flex
        direction="column"
        gap="4"
        justify="center"
        style={{ flex: "1 1 60%" }}
      >
        <Text wrap="pretty" size="4" color="teal" highContrast>
          A Full-stack web service for a ticket sales agency.
        </Text>
        <Text wrap="pretty" size="3" highContrast>
          Team: Janne Airaksinen, Paul Carlson, Jesse Hellman, Julia Hämäläinen
          & Tomi Lappalainen
        </Text>
        <Text wrap="pretty" size="3" highContrast>
          TicketGuru is a ticket sales system designed for tracking events,
          managing available tickets, and selling tickets to customers. The
          primary customer for the system is a ticket office, and the main users
          include ticket sellers working at physical sales counters, event
          coordinators, and system administrators.
        </Text>
        <Text wrap="pretty" size="3" highContrast>
          The system aims to improve the ticket office’s efficiency by
          simplifying ticket sales, providing a clear overview of events and
          ticket availability, and supporting decision-making through business
          reports generated by the system.
        </Text>
        <Text wrap="pretty" size="3" highContrast>
          The project is built using Java and the Spring Boot framework on the
          backend, with PostgreSQL as the relational database. The frontend uses
          JavaScript, React, and Tailwind, and the application is deployed on an
          NGINX server. The system is intended specifically for desktop use,
          with no tablet or mobile interfaces included. The final deliverable
          consists of a fully functional TicketGuru system along with its
          documentation.
        </Text>
        <Flex justify="center">
          <Link
            href="https://ticketguru.paulcarlson.fi"
            target="_blank"
            color="blue"
            underline="hover"
            size="6"
          >
            Try Ticketguru
            <OpenInNewWindowIcon
              style={{ width: "36px", height: "36px" }}
            />{" "}
          </Link>
        </Flex>
        <Text wrap="pretty" size="2" highContrast align="center">
          Login with admin@test.com / admin
        </Text>
        <Flex justify="center">
          <Link
            href="https://github.com/marttyyriroskis/nat20-ticketguru"
            target="_blank"
            color="gray"
            underline="hover"
            size="6"
          >
            GitHub Repository
            <GitHubLogoIcon style={{ width: "36px", height: "36px" }} />
          </Link>
        </Flex>
      </Flex>
    </Section>
  );
}
