name: Deploy Website
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/www/html
            git fetch --all
            git reset --hard origin/main

            VERSION="v$(git rev-list --count HEAD)"
            HASH=$(git rev-parse --short HEAD)
            DATE=$(date +"%d %b %Y")

            sed "s/__VERSION__/$VERSION/; s/__HASH__/$HASH/; s/__DATE__/$DATE/" index.template.html > index.html
